# Generated by Django 5.2.15 on 2026-07-02 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office'), ('Billing', 'Billing'), ('Warehouse', 'Warehouse')], default='Home', max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(default='English', max_length=200)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('pref_fragile', models.BooleanField(default=True)),
                ('pref_electronics', models.BooleanField(default=True)),
                ('pref_documents', models.BooleanField(default=True)),
                ('pref_liquid', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20)),
                ('kyc_document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('passport', 'International Passport')], default='national_id', max_length=20)),
                ('kyc_document_front', models.TextField(blank=True, null=True)),
                ('kyc_document_back', models.TextField(blank=True, null=True)),
                ('kyc_selfie', models.TextField(blank=True, null=True)),
                ('kyc_rejection_reason', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=1)),
                ('completed_trips', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
