# Generated by Django 5.2.16 on 2026-07-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_trust_score_alter_profile_kyc_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='document_passport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_passport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'Government ID'), ('passport', 'International Passport'), ('driving_license', 'Driving License'), ('national_id_and_passport', 'National ID & Passport')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='kyc_document_type',
            field=models.CharField(choices=[('national_id', 'Government ID'), ('passport', 'International Passport'), ('driving_license', 'Driving License'), ('national_id_and_passport', 'National ID & Passport')], default='national_id_and_passport', max_length=30),
        ),
    ]
