# Generated by Django 5.2.16 on 2026-07-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_kycdocument_document_passport_profile_kyc_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kyc_document_type',
            field=models.CharField(choices=[('national_id', 'Government ID'), ('passport', 'International Passport'), ('driving_license', 'Driving License'), ('national_id_and_passport', 'National ID & Passport')], default='national_id_and_passport', max_length=50),
        ),
    ]
