# Generated by Django 5.2.15 on 2026-07-02 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=100)),
                ('aircraft', models.CharField(blank=True, max_length=100, null=True)),
                ('from_location', models.CharField(max_length=150)),
                ('to_location', models.CharField(max_length=150)),
                ('from_airport', models.CharField(blank=True, max_length=150, null=True)),
                ('to_airport', models.CharField(blank=True, max_length=150, null=True)),
                ('departure_date', models.DateField()),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.CharField(max_length=20)),
                ('duration', models.CharField(default='2h', max_length=20)),
                ('terminal_from', models.CharField(blank=True, max_length=20, null=True)),
                ('terminal_to', models.CharField(blank=True, max_length=20, null=True)),
                ('seats', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity_weight', models.DecimalField(decimal_places=2, default=23.0, max_digits=5)),
                ('available_weight', models.DecimalField(decimal_places=2, default=23.0, max_digits=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['from_location', 'to_location'], name='trips_trip_from_lo_3bfd11_idx'), models.Index(fields=['departure_date'], name='trips_trip_departu_7bc4b1_idx'), models.Index(fields=['status'], name='trips_trip_status_259ca6_idx')],
            },
        ),
    ]
