# Generated by Django 5.2.15 on 2026-07-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='accepted_parcel_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Paused', 'Paused'), ('Archived', 'Archived'), ('Cancelled', 'Cancelled')], default='Active', max_length=20),
        ),
    ]
