# Generated by Django 5.2.16 on 2026-07-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_accepted_parcel_types_trip_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='transport_type',
            field=models.CharField(default='Flight', max_length=50),
        ),
    ]
