# Generated by Django 5.2.16 on 2026-07-31 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_notes_trip_transport_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user'], name='trips_trip_user_id_b0cf72_idx'),
        ),
    ]
