# Generated by Django 5.2.16 on 2026-07-27 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('AIRPORT_MEETING', 'AIRPORT_MEETING'), ('BAG_RECEIVED', 'BAG_RECEIVED'), ('IN_FLIGHT', 'IN_FLIGHT'), ('ARRIVED', 'ARRIVED'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('DISPUTED', 'DISPUTED')], default='REQUESTED', max_length=30)),
                ('escrow_status', models.CharField(choices=[('PENDING', 'PENDING'), ('HELD', 'HELD'), ('RELEASED', 'RELEASED'), ('REFUNDED', 'REFUNDED')], default='PENDING', max_length=20)),
                ('qr_code_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('meeting_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_point', models.CharField(blank=True, default='Departure Terminal Main Information Desk', max_length=255, null=True)),
                ('terminal', models.CharField(blank=True, default='T1', max_length=50, null=True)),
                ('gate', models.CharField(blank=True, default='Gate A4', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_bookings_as_booker', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_bookings_as_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LuggageDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('evidence_urls', models.TextField(blank=True, default='[]')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('UNDER_REVIEW', 'UNDER_REVIEW'), ('RESOLVED_BUYER', 'RESOLVED_BUYER'), ('RESOLVED_SELLER', 'RESOLVED_SELLER'), ('DISMISSED', 'DISMISSED')], default='OPEN', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='luggage_sharing.luggagebooking')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LuggageListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('flight_number', models.CharField(max_length=50)),
                ('departure_airport', models.CharField(max_length=100)),
                ('arrival_airport', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('cabin_class', models.CharField(choices=[('Economy', 'Economy'), ('Premium Economy', 'Premium Economy'), ('Business', 'Business'), ('First Class', 'First Class')], default='Economy', max_length=30)),
                ('max_airline_allowance', models.DecimalField(decimal_places=2, help_text='Max KG allowed by airline', max_digits=6)),
                ('currently_used_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('available_weight', models.DecimalField(decimal_places=2, help_text='Calculated: Max - Currently Used', max_digits=6)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_kg', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('max_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('accept_partial_booking', models.BooleanField(default=True)),
                ('instant_booking', models.BooleanField(default=False)),
                ('insurance', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='luggage_sharing.luggagelisting'),
        ),
        migrations.CreateModel(
            name='LuggageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_score', models.IntegerField(default=5)),
                ('punctuality_score', models.IntegerField(default=5)),
                ('behaviour_score', models.IntegerField(default=5)),
                ('accuracy_score', models.IntegerField(default=5)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='luggage_sharing.luggagebooking')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LuggageVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('QR_SCAN', 'QR_SCAN'), ('FACE_SELFIE', 'FACE_SELFIE'), ('GPS_VALIDATION', 'GPS_VALIDATION'), ('PASSPORT_CHECK', 'PASSPORT_CHECK'), ('AIRLINE_CHECK', 'AIRLINE_CHECK')], max_length=30)),
                ('selfie_image', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('device_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('qr_scanned_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='luggage_sharing.luggagebooking')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_verification_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LuggageWeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PICKUP', 'PICKUP'), ('AIRPORT', 'AIRPORT'), ('DESTINATION', 'DESTINATION')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo_evidence', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to='luggage_sharing.luggagebooking')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_weight_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='luggagelisting',
            index=models.Index(fields=['owner'], name='luggage_lis_owner_i_dd998e_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagelisting',
            index=models.Index(fields=['status'], name='luggage_lis_status_06e1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagelisting',
            index=models.Index(fields=['departure_airport', 'arrival_airport'], name='luggage_lis_departu_00e965_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagelisting',
            index=models.Index(fields=['departure_date'], name='luggage_lis_departu_e2b6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['booker'], name='luggage_boo_booker__5b23f4_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['owner'], name='luggage_boo_owner_i_54cd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['status'], name='luggage_boo_status_313c07_idx'),
        ),
        migrations.AddIndex(
            model_name='luggagebooking',
            index=models.Index(fields=['qr_code_token'], name='luggage_boo_qr_code_d51a32_idx'),
        ),
    ]
