# Generated by Django 5.2.16 on 2026-07-27 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage_sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luggageverificationlog',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='luggageverificationlog',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='luggageweightlog',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='luggageweightlog',
            name='logged_by',
        ),
        migrations.AddField(
            model_name='luggagebooking',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='luggagebooking',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('PAID', 'PAID'), ('VERIFIED', 'VERIFIED'), ('VERIFICATION_REJECTED', 'VERIFICATION_REJECTED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('ARRIVED', 'ARRIVED'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('DISPUTED', 'DISPUTED')], default='REQUESTED', max_length=30),
        ),
        migrations.CreateModel(
            name='LuggageOTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_entered', models.CharField(max_length=6)),
                ('is_success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_logs', to='luggage_sharing.luggagebooking')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_otp_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LuggageQRLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(max_length=100)),
                ('is_success', models.BooleanField(default=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_logs', to='luggage_sharing.luggagebooking')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_qr_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LuggageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('behaviour_score', models.IntegerField(default=5)),
                ('communication_score', models.IntegerField(default=5)),
                ('timing_score', models.IntegerField(default=5)),
                ('experience_score', models.IntegerField(default=5)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='luggage_sharing.luggagebooking')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_reviews_got', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_reviews_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LuggageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location_name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='luggage_sharing.luggagebooking')),
            ],
            options={
                'db_table': 'luggage_tracking',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LuggageVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_images', models.TextField(blank=True, default='[]', help_text='JSON array of uploaded image URLs')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('notes', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='luggage_sharing.luggagebooking')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'luggage_verifications',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='LuggageRating',
        ),
        migrations.DeleteModel(
            name='LuggageVerificationLog',
        ),
        migrations.DeleteModel(
            name='LuggageWeightLog',
        ),
    ]
