# Generated by Django 5.2.15 on 2026-07-10 13:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(db_index=True, max_length=20)),
                ('travel_date', models.DateField(db_index=True)),
                ('call_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('airline_name', models.CharField(blank=True, max_length=100, null=True)),
                ('airline_iata', models.CharField(blank=True, max_length=10, null=True)),
                ('airline_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('aircraft_model', models.CharField(blank=True, max_length=100, null=True)),
                ('aircraft_registration', models.CharField(blank=True, max_length=20, null=True)),
                ('aircraft_modes', models.CharField(blank=True, max_length=20, null=True)),
                ('flight_status', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo_status', models.CharField(blank=True, max_length=50, null=True)),
                ('codeshare_status', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('departure_airport_name', models.CharField(blank=True, max_length=150, null=True)),
                ('departure_airport_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_country', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_iata', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('departure_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('departure_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_scheduled_utc', models.DateTimeField(blank=True, null=True)),
                ('departure_scheduled_local', models.DateTimeField(blank=True, null=True)),
                ('departure_revised_utc', models.DateTimeField(blank=True, null=True)),
                ('departure_revised_local', models.DateTimeField(blank=True, null=True)),
                ('departure_runway_time', models.DateTimeField(blank=True, null=True)),
                ('departure_terminal', models.CharField(blank=True, max_length=20, null=True)),
                ('arrival_airport_name', models.CharField(blank=True, max_length=150, null=True)),
                ('arrival_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_country', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_icao', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_iata', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('arrival_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('arrival_timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_scheduled_utc', models.DateTimeField(blank=True, null=True)),
                ('arrival_scheduled_local', models.DateTimeField(blank=True, null=True)),
                ('arrival_revised_utc', models.DateTimeField(blank=True, null=True)),
                ('arrival_revised_local', models.DateTimeField(blank=True, null=True)),
                ('arrival_runway_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_runway', models.CharField(blank=True, max_length=20, null=True)),
                ('last_updated_utc', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'flights_flight',
                'ordering': ['-departure_scheduled_utc'],
                'constraints': [models.UniqueConstraint(fields=('flight_number', 'travel_date'), name='unique_flight_date')],
            },
        ),
    ]
