# Generated by Django 5.2.15 on 2026-07-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Package Received', 'Package Received'), ('In Transit', 'In Transit'), ('Customs Clearance', 'Customs Clearance'), ('Out for Handoff', 'Out for Handoff'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Package Received', max_length=50)),
                ('pickup_address', models.CharField(max_length=300)),
                ('delivery_address', models.CharField(max_length=300)),
                ('dimensions', models.CharField(default='Standard size', max_length=100)),
                ('insurance', models.CharField(choices=[('Insured ($500 limit)', 'Insured ($500 limit)'), ('Basic Coverage', 'Basic Coverage'), ('No Insurance', 'No Insurance')], default='Basic Coverage', max_length=50)),
                ('eta', models.CharField(default='Next 3-5 days', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='shipments_s_trackin_80db53_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
    ]
