# Generated by Django 5.2.16 on 2026-07-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_category_shipment_declared_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentimage',
            name='image_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('package', 'Package'), ('proof', 'Proof'), ('damage', 'Damage')], default='package', max_length=20),
        ),
    ]
