# Generated by Django 5.2.16 on 2026-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
