# Generated by Django 5.2.16 on 2026-07-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_delivery_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('REQUEST_CREATED', 'REQUEST_CREATED'), ('MATCH_FOUND', 'MATCH_FOUND'), ('REQUEST_SENT', 'REQUEST_SENT'), ('REQUEST_RECEIVED', 'REQUEST_RECEIVED'), ('ACCEPTED', 'ACCEPTED'), ('PAID', 'PAID'), ('PARCEL_VERIFIED', 'PARCEL_VERIFIED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('ARRIVED', 'ARRIVED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('OTP_GENERATED', 'OTP_GENERATED'), ('DELIVERED', 'DELIVERED'), ('PAYMENT_RELEASED', 'PAYMENT_RELEASED'), ('RATED', 'RATED'), ('DISPUTE_OPENED', 'DISPUTE_OPENED'), ('DISPUTE_APPROVED', 'DISPUTE_APPROVED'), ('DISPUTE_REJECTED', 'DISPUTE_REJECTED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED')], default='REQUEST_CREATED', max_length=30),
        ),
    ]
