# Generated by Django 5.2.16 on 2026-07-25 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_delivery_date_booking_receiver_address_and_more'),
        ('trips', '0003_trip_notes_trip_transport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sender_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_bookings', to='trips.trip'),
        ),
    ]
