# Generated by Django 5.2.16 on 2026-07-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_sender_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('REQUEST_CREATED', 'REQUEST_CREATED'), ('MATCH_FOUND', 'MATCH_FOUND'), ('REQUEST_SENT', 'REQUEST_SENT'), ('REQUEST_RECEIVED', 'REQUEST_RECEIVED'), ('ACCEPTED', 'ACCEPTED'), ('PAID', 'PAID'), ('PARCEL_VERIFIED', 'PARCEL_VERIFIED'), ('IN_TRANSIT', 'IN_TRANSIT'), ('ARRIVED', 'ARRIVED'), ('OUT_FOR_DELIVERY', 'OUT_FOR_DELIVERY'), ('OTP_GENERATED', 'OTP_GENERATED'), ('DELIVERED', 'DELIVERED'), ('PAYMENT_RELEASED', 'PAYMENT_RELEASED'), ('RATED', 'RATED'), ('DISPUTE_OPENED', 'DISPUTE_OPENED'), ('DISPUTE_APPROVED', 'DISPUTE_APPROVED'), ('DISPUTE_REJECTED', 'DISPUTE_REJECTED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('Draft', 'Draft'), ('Waiting Traveller', 'Waiting Traveller'), ('Booking Requested', 'Booking Requested'), ('Traveller Accepted', 'Traveller Accepted'), ('Payment Pending', 'Payment Pending'), ('Payment Completed', 'Payment Completed'), ('Pickup Scheduled', 'Pickup Scheduled'), ('Parcel Verification', 'Parcel Verification'), ('Risk Analysis', 'Risk Analysis'), ('Ready For Transit', 'Ready For Transit'), ('In Transit', 'In Transit'), ('Flight Landed', 'Flight Landed'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='REQUEST_CREATED', max_length=30),
        ),
    ]
