# Generated by Django 5.2.16 on 2026-07-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIKnowledgeBaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('platform', 'Platform & How It Works'), ('traveller', 'Traveller Workflow & Earning'), ('sender', 'Sender & Package Delivery'), ('security', 'Safety, KYC & Security'), ('prohibited_items', 'Prohibited Items & Illegal Goods'), ('payments', 'Escrow, Wallet & Payments'), ('disputes', 'Disputes & Cancellations')], default='platform', max_length=50)),
                ('question', models.CharField(help_text='Question or trigger keyword phrase', max_length=255)),
                ('answer', models.TextField(help_text='Factual answer or policy response text')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
