# Generated by Django 5.2.16 on 2026-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=255)),
                ('template', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('event', models.CharField(default='general', max_length=100)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('PREVIEW', 'Preview')], default='QUEUED', max_length=20)),
                ('provider', models.CharField(default='Resend', max_length=50)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
